# Generated by Django 5.2.1 on 2025-05-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicedepoiment',
            options={'verbose_name': 'Depoimento do Serviço', 'verbose_name_plural': 'Depoimentos dos Serviços'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Imagem do Serviço', 'verbose_name_plural': 'Imagens dos Serviços'},
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(default=1, max_length=255, verbose_name='Descrição Curta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
