# Generated by Django 5.2.1 on 2025-05-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_alter_servicedepoiment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(default='Descrição do serviço', max_length=255, verbose_name='Descrição Curta'),
        ),
    ]
